dist: trusty
sudo: false
language: python
python:
  - 2.7
  - 3.6
  - nightly
install:
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt
script:
  - pytest tests.py
notifications:
  email: false
